In [12]:
%pip install pandas
import pandas as pd
import os

Requirement already satisfied: pandas in c:\Users\gabriel.pessoli_v4co\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\gabriel.pessoli_v4co\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\gabriel.pessoli_v4co\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\Users\gabriel.pessoli_v4co\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\Users\gabriel.pessoli_v4co\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\gabriel.pessoli_v4co\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~ip (c:\Users\gabriel.pessoli_v4co\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\gabriel.pessoli_v4co\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\gabriel.pessoli_v4co\AppData\Local\Programs\Python\Python313\Lib\site-packages)

In [13]:
arquivos = [
    "./2024/comprasGOV-anual-VW_DM_PNCP_ITEM_RESULTADO-2024.csv",
    "./2024/comprasGOV-anual-VW_FT_PNCP_COMPRA_ITEM-2024.csv",
    "./2024/comprasGOV-anual-VW_FT_PNCP_COMPRA-2024.csv",
    "./2025/comprasGOV-anual-VW_DM_PNCP_ITEM_RESULTADO-2025.csv",
    "./2025/comprasGOV-anual-VW_FT_PNCP_COMPRA_ITEM-2025.csv",
    "./2025/comprasGOV-anual-VW_FT_PNCP_COMPRA-2025.csv"
]

lista_compra = []
lista_item = []
lista_resultado = []

print("Iniciando a leitura e separação dos arquivos...\n")

for caminho in arquivos:
    nome_arquivo = os.path.basename(caminho)
    print(f"Lendo: {nome_arquivo}")
    
    try:
        df_temp = pd.read_csv(caminho, sep=',', encoding='utf-8')
        
        if 'COMPRA_ITEM' in nome_arquivo:
            lista_item.append(df_temp)
        elif 'ITEM_RESULTADO' in nome_arquivo:
            lista_resultado.append(df_temp)
        elif 'COMPRA-' in nome_arquivo: 
            lista_compra.append(df_temp)
            
    except Exception as e:
        print(f"Erro ao ler {nome_arquivo}: {e}")

print("\nUnificando as bases...")

df_compra_final = pd.concat(lista_compra, ignore_index=True)
df_item_final = pd.concat(lista_item, ignore_index=True)
df_resultado_final = pd.concat(lista_resultado, ignore_index=True)

print(f"Base de COMPRAS unificada com {len(df_compra_final)} linhas.")
print(f"Base de ITENS unificada com {len(df_item_final)} linhas.")
print(f"Base de RESULTADOS unificada com {len(df_resultado_final)} linhas.")

Iniciando a leitura e separação dos arquivos...

Lendo: comprasGOV-anual-VW_DM_PNCP_ITEM_RESULTADO-2024.csv

C:\Users\gabriel.pessoli_v4co\AppData\Local\Temp\ipykernel_23752\3176372603.py:21: DtypeWarning: Columns (1,5,34,39,44) have mixed types. Specify dtype option on import or set low_memory=False.
  df_temp = pd.read_csv(caminho, sep=',', encoding='utf-8')

Lendo: comprasGOV-anual-VW_FT_PNCP_COMPRA_ITEM-2024.csv

C:\Users\gabriel.pessoli_v4co\AppData\Local\Temp\ipykernel_23752\3176372603.py:21: DtypeWarning: Columns (8,33) have mixed types. Specify dtype option on import or set low_memory=False.
  df_temp = pd.read_csv(caminho, sep=',', encoding='utf-8')

Lendo: comprasGOV-anual-VW_FT_PNCP_COMPRA-2024.csv

C:\Users\gabriel.pessoli_v4co\AppData\Local\Temp\ipykernel_23752\3176372603.py:21: DtypeWarning: Columns (3,8,9,10,18,20,21,22,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df_temp = pd.read_csv(caminho, sep=',', encoding='utf-8')

Lendo: comprasGOV-anual-VW_DM_PNCP_ITEM_RESULTADO-2025.csv

C:\Users\gabriel.pessoli_v4co\AppData\Local\Temp\ipykernel_23752\3176372603.py:21: DtypeWarning: Columns (5,34,39,44) have mixed types. Specify dtype option on import or set low_memory=False.
  df_temp = pd.read_csv(caminho, sep=',', encoding='utf-8')

Lendo: comprasGOV-anual-VW_FT_PNCP_COMPRA_ITEM-2025.csv

C:\Users\gabriel.pessoli_v4co\AppData\Local\Temp\ipykernel_23752\3176372603.py:21: DtypeWarning: Columns (33,39,52,53,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df_temp = pd.read_csv(caminho, sep=',', encoding='utf-8')

Lendo: comprasGOV-anual-VW_FT_PNCP_COMPRA-2025.csv

C:\Users\gabriel.pessoli_v4co\AppData\Local\Temp\ipykernel_23752\3176372603.py:21: DtypeWarning: Columns (8,9,10,18,20,21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  df_temp = pd.read_csv(caminho, sep=',', encoding='utf-8')

Unificando as bases...
Base de COMPRAS unificada com 618846 linhas.
Base de ITENS unificada com 6379194 linhas.
Base de RESULTADOS unificada com 4395570 linhas.

In [11]:
df_resultado_final.columns

Index(['srk_item_resultado', 'id_compra', 'id_compra_item',
       'id_contratacao_pncp', 'data_atualizacao', 'ni_fornecedor',
       'tipo_pessoa', 'data_inclusao', 'numero_item', 'data_cancelamento',
       'nome_razao_social_fornecedor', 'codigo_pais', 'porte_fornecedor_id',
       'quantidade_homologada', 'valor_unitario_homologado',
       'valor_total_homologado', 'percentual_desconto',
       'indicador_subcontratacao', 'ordem_classificacao_srp', 'data_resultado',
       'motivo_cancelamento', 'numero_controle_PNCP_compra',
       'porte_fornecedor_nome', 'situacao_compra_item_resultado_nome',
       'sequencial_resultado', 'natureza_juridica_nome',
       'natureza_juridica_id', 'situacao_compra_item_resultado_id',
       'orgao_entidade_cnpj', 'sequencial_compra', 'ano_compra',
       'unidade_orgao_codigo_unidade', 'aplicacao_margem_preferencia',
       'amparo_legal_margem_preferencia_id',
       'amparo_legal_margem_preferencia_nome',
       'amparo_legal_margem_preferencia_descricao',
       'aplicacao_beneficio_meepp', 'aplicacao_criterio_desempate',
       'amparo_legal_criterio_desempate_id',
       'amparo_legal_criterio_desempate_nome',
       'amparo_legal_criterio_desempate_descricao', 'moeda_estrangeira_id',
       'data_cotacao_moeda_estrangeira', 'valor_nominal_moeda_estrangeira',
       'pais_origem_produto_servico_id', 'timezone_cotacao_moeda_estrangeira',
       'data_atualizacao_pncp', 'data_inclusao_pncp', 'numero_item_pncp',
       'data_cancelamento_pncp', 'data_resultado_pncp',
       'unidade_orgao_uf_sigla'],
      dtype='object')

In [13]:
df_item_final[df_item_final["TXT_LINK_GRUPO"].notna()]

,srk_pncp_item_compra,cod_compra,cod_item_compra,codigo_classe,codigo_grupo,numero_item,numero_grupo,numero_item_compra,descricao_detalhada,descricao,...,descricao_resumida,item_categoria_id_pncp,criterio_julgamento_id_pncp,data_inclusao_pncp,data_atualizacao_pncp,numero_controle_PNCP_compra,TXT_LINK_MATERIAL,TXT_LINK_CLASSE,TXT_LINK_SERVICO,TXT_LINK_GRUPO
1642583,8687430,6332060,13262964,NaN,831.0,NaN,0,19,Estudos e Projetos de Estruturas - Metálicas,NaN,...,Estudos e Projetos de Estruturas - Metálicas,3.0,1.0,2024-06-19 07:13:42,2025-03-25 10:46:05,05058458000115-1-000052/2024,NaN,NaN,https://dadosabertos.compras.gov.br/modulo-ser...,https://dadosabertos.compras.gov.br/modulo-ser...
1642584,16080376,7466517,21176306,NaN,831.0,NaN,0,2,Projeto de Estrutura Metálica,NaN,...,Estudos e Projetos de Estruturas - Metálicas,3.0,1.0,2024-12-03 07:17:55,2025-01-28 15:35:21,76977768000181-1-000184/2024,NaN,NaN,https://dadosabertos.compras.gov.br/modulo-ser...,https://dadosabertos.compras.gov.br/modulo-ser...
1642585,2602917,5545422,6825126,NaN,831.0,NaN,0,4,Elaboração de projeto executivo de estruturas ...,NaN,...,Estudos e projetos de estruturas - metálicas,3.0,1.0,2023-09-28 07:04:51,2025-03-14 08:54:09,76206499000150-1-000112/2023,NaN,NaN,https://dadosabertos.compras.gov.br/modulo-ser...,https://dadosabertos.compras.gov.br/modulo-ser...
1642586,5389272,5898822,9732586,NaN,831.0,NaN,0,4,Projeto Estrutural De Estrutura Metálica - ate...,NaN,...,Estudos e projetos de estruturas - metálicas,3.0,1.0,2024-03-28 07:06:54,2025-03-23 04:54:22,78200482000110-1-000019/2024,NaN,NaN,https://dadosabertos.compras.gov.br/modulo-ser...,https://dadosabertos.compras.gov.br/modulo-ser...
1642587,8448287,6270435,12938138,NaN,831.0,NaN,0,1,Estudos e Projetos de Estruturas - Metálicas,NaN,...,Estudos e Projetos de Estruturas - Metálicas,3.0,1.0,2024-06-12 08:23:32,2025-03-27 01:42:42,00508903000188-1-001171/2024,NaN,NaN,https://dadosabertos.compras.gov.br/modulo-ser...,https://dadosabertos.compras.gov.br/modulo-ser...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6045542,34163465,9452433,40616684,NaN,931.0,NaN,0,1,Tratamento neuropsicológico ambulatorial/clíni...,NaN,...,Tratamento neuropsicológico ambulatorial/clíni...,3.0,7.0,2025-10-07 12:59:34,2025-10-07 13:02:34,46374500000194-1-009936/2025,NaN,NaN,https://dadosabertos.compras.gov.br/modulo-ser...,https://dadosabertos.compras.gov.br/modulo-ser...
6045543,36690528,9423265,40222664,NaN,931.0,NaN,0,1,Tratamento Neuropsicológico Ambulatorial/Clínico,NaN,...,Tratamento Neuropsicológico Ambulatorial/Clínico,3.0,1.0,2025-10-02 07:26:18,2025-11-05 08:28:13,46374500000194-1-009738/2025,NaN,NaN,https://dadosabertos.compras.gov.br/modulo-ser...,https://dadosabertos.compras.gov.br/modulo-ser...
6045544,38157322,9242150,37944373,NaN,931.0,NaN,0,1,Tratamento Neuropsicológico Ambulatorial/Clínico,NaN,...,Tratamento Neuropsicológico Ambulatorial/Clínico,3.0,1.0,2025-09-02 07:31:57,2025-11-28 15:05:12,46189734000161-1-000057/2025,NaN,NaN,https://dadosabertos.compras.gov.br/modulo-ser...,https://dadosabertos.compras.gov.br/modulo-ser...
6045545,38157322,9242150,37944373,NaN,931.0,NaN,0,1,Tratamento Neuropsicológico Ambulatorial/Clínico,NaN,...,Tratamento Neuropsicológico Ambulatorial/Clínico,3.0,1.0,2025-09-02 07:31:57,2025-11-28 15:05:12,46189734000161-1-000057/2025,NaN,NaN,https://dadosabertos.compras.gov.br/modulo-ser...,https://dadosabertos.compras.gov.br/modulo-ser...
6045546,35630111,9536991,41682785,NaN,931.0,NaN,0,1,Tratamento Neuropsicológico Ambulatorial/Clíni...,NaN,...,Tratamento Neuropsicológico Ambulatorial/Clíni...,3.0,7.0,2025-10-21 11:11:09,2025-10-21 11:14:10,00394452000103-1-021217/2025,NaN,NaN,https://dadosabertos.compras.gov.br/modulo-ser...,https://dadosabertos.compras.gov.br/modulo-ser...

In [15]:
df_item_final[df_item_final["codigo_grupo"] == 622]

,srk_pncp_item_compra,cod_compra,cod_item_compra,codigo_classe,codigo_grupo,numero_item,numero_grupo,numero_item_compra,descricao_detalhada,descricao,...,descricao_resumida,item_categoria_id_pncp,criterio_julgamento_id_pncp,data_inclusao_pncp,data_atualizacao_pncp,numero_controle_PNCP_compra,TXT_LINK_MATERIAL,TXT_LINK_CLASSE,TXT_LINK_SERVICO,TXT_LINK_GRUPO
156504,13743272,7138830,18509001,NaN,622.0,2.0,0,2,"GRADE NIVELADORA CONTROLE REMOTO 28X20X4,50 MM...",Comercialização de Produtos Agropecuários,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156541,13748892,7138830,18509000,NaN,622.0,1.0,0,1,"PLAINA HIDRAULICA NIVELADORA, EQUIVALENTE TECN...",Comercialização de Produtos Agropecuários,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156542,11599577,6775742,16156168,NaN,622.0,1.0,0,1,ADUBO 10 10 10 NPK para gramado contendo nit...,Comercialização de Produtos Agropecuários,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156543,11601140,6775742,16156171,NaN,622.0,4.0,0,4,"FORMICIDA EM PÓ INSETICIDA PIRETRÓIDE, PÓ DE...",Comercialização de Produtos Agropecuários,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156544,11599578,6775742,16156170,NaN,622.0,3.0,0,3,FORMICIDA LÍQUIDO INSETICIDA PIRETRÓIDE COM ...,Comercialização de Produtos Agropecuários,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156545,11599579,6775742,16156177,NaN,622.0,10.0,0,10,HERBICIDA GLIFOSATO N.A. Classe: Herbicida Sis...,Comercialização de Produtos Agropecuários,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156546,11606179,6775742,16156173,NaN,622.0,6.0,0,6,CUPINICIDA Classe: Inseticida/Cupinicida Grup...,Comercialização de Produtos Agropecuários,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156620,11612311,6775742,16156175,NaN,622.0,8.0,0,8,VERMICULITA EXPANDIDA FINA 100 LITROS USO AG...,Comercialização de Produtos Agropecuários,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156621,11601302,6775742,16156169,NaN,622.0,2.0,0,2,ADUBO QUIMICO 4-14-8 SACO DE 50 KG adubo min...,Comercialização de Produtos Agropecuários,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156622,11606178,6775742,16156172,NaN,622.0,5.0,0,5,FORMICIDA GRANULADO INDICADO PARA O CONTROLE...,Comercialização de Produtos Agropecuários,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156623,11601843,6775742,16156174,NaN,622.0,7.0,0,7,"Cupinicida Cipermetrina 5%, inseticida com a...",Comercialização de Produtos Agropecuários,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156624,11601141,6775742,16156176,NaN,622.0,9.0,0,9,UREIA PARA ADUBAÇÃO QUIMICA SACO CONTENDO 50 K...,Comercialização de Produtos Agropecuários,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1943181,9140304,6410311,13699713,NaN,622.0,NaN,0,5,FEIJAO DE 1ª QUALIDADE TIPO 1 PCT DE 1 KG CARI...,NaN,...,Comercialização de Grão,3.0,1.0,2024-06-27 07:08:46,2025-03-27 15:43:58,04092672000125-1-000067/2024,NaN,NaN,https://dadosabertos.compras.gov.br/modulo-ser...,https://dadosabertos.compras.gov.br/modulo-ser...
2065427,19994321,8034555,25701671,NaN,622.0,NaN,0,2,"Isca Granulada, para controle de formiga corta...",NaN,...,Comercialização de Produtos Agropecuários,3.0,1.0,2025-03-17 07:36:26,2025-04-07 15:15:15,77817476000144-1-000002/2025,NaN,NaN,https://dadosabertos.compras.gov.br/modulo-ser...,https://dadosabertos.compras.gov.br/modulo-ser...